# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - WF-Inventory

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5e807005347049c59d0192577774cf0a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_46fe8849ba5c47a5afec468634c536bf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5e807005347049c59d0192577774cf0a }}/wf-inventory:${{ github.sha }}
        file: ./docker/8.2/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'WF-Inventory'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d707afeb212f4275aa82d7c542ae49af }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5e807005347049c59d0192577774cf0a }}/wf-inventory:${{ github.sha }}'
